"""empty message

Revision ID: 2047b23dd5ca
Revises: 
Create Date: 2021-06-02 11:53:45.563575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2047b23dd5ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_review', sa.TEXT(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('book')
    # ### end Alembic commands ###
